#chapter 1
print(260+260)
print("ZCYN")
print('hello '*3)
print('hello '+'zcyn')
her_name=input('请输入她的名字：')
print("她的名字是：",her_name)
print('她名字的长度是：',len(her_name))
print(len(str(520)+'子济'))
print(int('1')+int('1'))
print(int(0.5))
